/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ConfirmarEntradaEsaida;

import ConfirmarEntradaEsaida.ConfirmarEntradaVeiculoMudanca;
import Controle.AtualizadoHora;
import Controle.ConectaBanco;
import Modelo.ModeloTabela;
import Visao.Principal;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.JButton;
/**
 *
 * @author Eduardo
 */
public class EntradaMoradorEVeiculo extends javax.swing.JFrame {

    ConectaBanco conex = new ConectaBanco();
    public EntradaMoradorEVeiculo() {
        initComponents();
        
        this.setExtendedState(getExtendedState()| EntradaMoradorEVeiculo.MAXIMIZED_BOTH);
        
         URL url = this.getClass().getResource("/Imagens/condominio.jpg");  //coloca a imagem no lugar da tigela java
          Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
            this.setIconImage(imagemTitulo);
        
        AtualizadoHora.start(Hora); // Para colocar a Hora no sistema
        
        
        //Pega data do sistema
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        Data.setText(df.format(hoje));
        
        
        




//faz os botões serem acionados com a tecla enter
    AbstractAction action = new AbstractAction() {
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() instanceof JButton){
        JButton button = (JButton) e.getSource();
        button.doClick();        
        } else if(e.getSource() instanceof JComponent){
            JComponent component = (JComponent) e.getSource();
            component.transferFocus();
        }
    }
    };
    
    jButtonIniciar.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonIniciar.getActionMap().put("DoClick", action);
    jButtonBuscar.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonBuscar.getActionMap().put("DoClick", action);
    jButtonConfirmar.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonConfirmar.getActionMap().put("DoClick", action);
    jButtonAgendar.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonAgendar.getActionMap().put("DoClick", action);
    jButtonBaixa.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonBaixa.getActionMap().put("DoClick", action);

    
    
        
        jButtonConfirmar.setEnabled(false);
        jButtonBaixa.setEnabled(false);
        jTextArea1.setEditable(false);
        jComboBoxBloco.setEnabled(false);
        jComboBoxApartamento.setEnabled(false);
        jButtonBuscar.setEnabled(false);
        jButtonConfirmar.setEnabled(false);
        jButtonAgendar.setEnabled(false);
        jTable1.setEnabled(false);
        
        preencherTabelaMudanca("select idMudanca,bloco,numeroApartamento,nomeMorador,dataMudanca,horaMudanca,tipo from mudanca ");
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Data = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codMu = new javax.swing.JLabel();
        codMorador = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxApartamento = new javax.swing.JComboBox();
        jButtonBuscar = new javax.swing.JButton();
        jComboBoxBloco = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonBaixa = new javax.swing.JButton();
        jLabelDataMudanca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jButtonAgendar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonIniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Condominio-SJ2");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        Data.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Data.setForeground(new java.awt.Color(255, 255, 255));
        Data.setText("Data");

        Hora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Hora.setForeground(new java.awt.Color(255, 255, 255));
        Hora.setText("Hora");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirmar Mudança de morador com veículos");

        codMu.setForeground(new java.awt.Color(204, 204, 204));
        codMu.setText("Cod Mudança");

        codMorador.setForeground(new java.awt.Color(204, 204, 204));
        codMorador.setText("Cod Morador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codMu)
                        .addGap(318, 318, 318)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codMorador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 993, Short.MAX_VALUE)
                        .addComponent(Data)
                        .addGap(108, 108, 108)
                        .addComponent(Hora)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codMu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Data)
                            .addComponent(Hora)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codMorador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jComboBoxApartamento.setForeground(new java.awt.Color(0, 204, 0));
        jComboBoxApartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "APARTAMENTO 101", "APARTAMENTO 102", "APARTAMENTO 103", "APARTAMENTO 104", "APARTAMENTO 201", "APARTAMENTO 202", "APARTAMENTO 203", "APARTAMENTO 204", "APARTAMENTO 301", "APARTAMENTO 302", "APARTAMENTO 303", "APARTAMENTO 304", "APARTAMENTO 401", "APARTAMENTO 402", "APARTAMENTO 403", "APARTAMENTO 404", " ", " " }));

        jButtonBuscar.setForeground(new java.awt.Color(51, 204, 0));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesq.png"))); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setToolTipText("Buscar agendamento");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jComboBoxBloco.setForeground(new java.awt.Color(0, 204, 0));
        jComboBoxBloco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLOCO A", "BLOCO B", "BLOCO C", "BLOCO D", "BLOCO F", "BLOCO G", "BLOCO H", "BLOCO I", "BLOCO J", "BLOCO K", " ", " " }));

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 153, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonBaixa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBaixa.setForeground(new java.awt.Color(255, 51, 51));
        jButtonBaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        jButtonBaixa.setText("Retirar do agendamento");
        jButtonBaixa.setToolTipText("Selecio a linha que deseja dar baixa e clique aqui!");
        jButtonBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaixaActionPerformed(evt);
            }
        });

        jLabelDataMudanca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelDataMudanca.setForeground(new java.awt.Color(102, 153, 255));
        jLabelDataMudanca.setText("Data / /");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mudança agendada para o dia");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Situação:");

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 51, 51));
        jLabelTipo.setText("Tipo");

        jButtonConfirmar.setForeground(new java.awt.Color(51, 153, 0));
        jButtonConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setToolTipText("Confirmar entrada");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jButtonAgendar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAgendar.setForeground(new java.awt.Color(255, 102, 0));
        jButtonAgendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        jButtonAgendar.setText("Agendados");
        jButtonAgendar.setToolTipText("Agendados");
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(102, 204, 255));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButtonIniciar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(51, 51, 255));
        jButtonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("Realizar entrada do morador agendado");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Selicione uma linha  e clique no botão : Retirar do agendamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(jLabelDataMudanca))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jComboBoxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(140, 140, 140)
                                .addComponent(jLabelTipo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonAgendar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButtonIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAgendar)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar)
                            .addComponent(jComboBoxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataMudanca)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabel2))
                        .addGap(13, 13, 13)
                        .addComponent(jButtonConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBaixa))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaixaActionPerformed
        /*
          String entrada="Entrada Confirmada";  
    conex.execultasql("select * from mudanca where idMudanca='"+codMu.getText()+"' and tipo='"+entrada+"'");
         try {              
              conex.rs.first(); 
               jLabelDataMudanca.setText(conex.rs.getString("dataMudanca"));   
               jTextArea1.setText(conex.rs.getString("nomeMorador"));  
               jLabelTipo.setText(conex.rs.getString("tipo"));  
               
               JOptionPane.showMessageDialog(rootPane,"Impossível!!");                
                JOptionPane.showMessageDialog(rootPane,"A entrada já foi realizada!!");
                dispose();
                
           } catch (SQLException ex1) {*/
        
        /////////////////////////////////////////////////   
        String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja dar Baixa ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;  //Este é o Botao do NAO. Ira retornar para a Calculadora
        }
        
        if(resposta == 0){  
            
            
             try {
           
                 
                 String bloco=String.valueOf(jComboBoxBloco.getSelectedItem());
                 String apt=String.valueOf(jComboBoxApartamento.getSelectedItem());
                 
    new BaixaMudanca(codMu.getText(),bloco,apt).setVisible(rootPaneCheckingEnabled);
           
          
          
            PreparedStatement delAgenda=conex.conn.prepareStatement("call deleteAgendamento('"+codMu.getText()+"')");
               
            delAgenda.execute();
               
            dispose();
            
            
             
     	
             
        } catch (SQLException ex) {
            
            
                JOptionPane.showMessageDialog(rootPane,"Erro delAgenda    "+ex);
      }
            
               
       
        
        //}     
        
        
            
               
    }

               
          /////////////////////////////////////////////////   
              
             
           
     
    }//GEN-LAST:event_jButtonBaixaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        
        
        conex.conexao();
        
   
        /////////////////////////Busca o ultimo id e a maior data
        conex.execultasql("select max(idMudanca) as idMudanca,idMorador from mudanca where  bloco='"+jComboBoxBloco.getSelectedItem()+"' and numeroApartamento='"+jComboBoxApartamento.getSelectedItem()+"'");
          try {         
               
               conex.rs.first();
               codMu.setText(String.valueOf(conex.rs.getInt("idMudanca"))); 
               codMorador.setText(String.valueOf(conex.rs.getInt("idMorador"))); 
               
               jButtonConfirmar.setEnabled(!false);
               jButtonAgendar.setEnabled(false);
                         
             } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane,"Não foi possível");
           

} 
        ////////////////////////////////////////////////////////////Fim        
        
        
        
   ////////////////////////Resgata o Ultimo id da mudança selecionado acima
      //String entrada="Entrada";  
    conex.execultasql("select * from mudanca where idMudanca='"+codMu.getText()+"'");
         try {              
              conex.rs.first(); 
               jLabelDataMudanca.setText(conex.rs.getString("dataMudanca"));   
               jTextArea1.setText(conex.rs.getString("nomeMorador"));  
               jLabelTipo.setText(conex.rs.getString("tipo"));  
               
           } catch (SQLException ex) {
               
              
               
           JOptionPane.showMessageDialog(rootPane,"Não foi possível");
              dispose();
}
        
        ////////////////////////////////Fim
       
       
         
         
     
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        
         
        String entrada="Entrada Confirmada";  
    conex.execultasql("select * from mudanca where idMudanca='"+codMu.getText()+"' and tipo='"+entrada+"'");
         try {              
              conex.rs.first(); 
               jLabelDataMudanca.setText(conex.rs.getString("dataMudanca"));   
               jTextArea1.setText(conex.rs.getString("nomeMorador"));  
               jLabelTipo.setText(conex.rs.getString("tipo"));  
               
               JOptionPane.showMessageDialog(rootPane,"Impossível!!");                
                JOptionPane.showMessageDialog(rootPane,"A entrada já foi realizada!!");
                dispose();
                
           } catch (SQLException ex1) {
               
              
               
          /////////////////////////////////////////////////   
        String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja Salvar ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;  //Este é o Botao do NAO. Ira retornar para a Calculadora
        }
        
        if(resposta == 0){  
            
            
            try {
            //Este é o Botao do SIM. Ira sair do seu Programa
            
            
            PreparedStatement confirmar=conex.conn.prepareStatement("call updateDataMudancaEHoraMudanca('"+codMu.getText()+"','"+codMorador.getText()+"','"+Hora.getText()+"')");
                confirmar.execute();
                //JOptionPane.showMessageDialog(rootPane,"Mudança realizada com sucesso");
            dispose();
            
            
             new ConfirmarEntradaVeiculoMudanca(codMu.getText(),String.valueOf(jComboBoxBloco.getSelectedItem()),String.valueOf(jComboBoxApartamento.getSelectedItem())).setVisible(true);
             
          
     	
             
        } catch (SQLException ex) {
            
            
                JOptionPane.showMessageDialog(rootPane,"Erro"+ex);
      }
            
               
    }
    ///////////////////////////////////////////////////////////////////////  

}
       
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        // TODO add your handling code here:
        jTable1.setEnabled(!false);
        jComboBoxBloco.setEnabled(false);
        jComboBoxApartamento.setEnabled(false);
        jButtonBuscar.setEnabled(false);
        jButtonConfirmar.setEnabled(false);
        jButtonBaixa.setEnabled(false);
        
        jTextArea1.setText("");
        jLabelDataMudanca.setText("");
        jLabelTipo.setText("");
        String b="BLOCO A";
        String a="APARTAMENTO 101";
        jComboBoxBloco.setSelectedItem(b);
        jComboBoxApartamento.setSelectedItem(a);
        
        String agendado = "Morador Agendado";
        preencherTabelaMudanca("select idMudanca,bloco,numeroApartamento,nomeMorador,dataMudanca,horaMudanca,tipo from mudanca where tipo='"+agendado+"'");
       
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        
        String id = ""+ jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        codMu.setText(id);
        
        String bloco = ""+ jTable1.getValueAt(jTable1.getSelectedRow(), 1);
        jComboBoxBloco.setSelectedItem(bloco);
        
        String apt = ""+ jTable1.getValueAt(jTable1.getSelectedRow(), 2);
        jComboBoxApartamento.setSelectedItem(apt);
        
        String morador = ""+ jTable1.getValueAt(jTable1.getSelectedRow(), 3);
        jTextArea1.setText(morador);
        
        String dataMud = ""+ jTable1.getValueAt(jTable1.getSelectedRow(), 4);
        jLabelDataMudanca.setText(dataMud);
         
        String tipo = ""+ jTable1.getValueAt(jTable1.getSelectedRow(), 6);
        jLabelTipo.setText(tipo);
        
        jButtonBaixa.setEnabled(!false);
       
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
        
        jButtonConfirmar.setEnabled(!false);
        jButtonBaixa.setEnabled(false);
        jTextArea1.setEditable(!false);
        jComboBoxBloco.setEnabled(!false);
        jComboBoxApartamento.setEnabled(!false);
        jButtonBuscar.setEnabled(!false);
        jButtonConfirmar.setEnabled(false);
        jButtonAgendar.setEnabled(!false);
        jTable1.setEnabled(false);
          
        jTextArea1.setText("");
        jLabelDataMudanca.setText("");
        jLabelTipo.setText("");
        String b="BLOCO A";
        String a="APARTAMENTO 101";
        jComboBoxBloco.setSelectedItem(b);
        jComboBoxApartamento.setSelectedItem(a);
        
         preencherTabelaMudanca("select idMudanca,bloco,numeroApartamento,nomeMorador,dataMudanca,horaMudanca,tipo from mudanca ");
         
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    
    public void preencherTabelaMudanca(String sql){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Codigo","Bloco","Apartamento","Morador","Data","Hora","tipo"};
       
     
        
        conex.conexao();
        conex.execultasql(sql);                
            try {
                conex.rs.first();
                do {
                  
                    dados.add(new Object[]{conex.rs.getString("idMudanca"),conex.rs.getString("bloco"),conex.rs.getString("numeroApartamento"),conex.rs.getString("nomeMorador"),conex.rs.getString("dataMudanca"),conex.rs.getString("horaMudanca"),conex.rs.getString("tipo")});
                    
                    
                   
                   
                }while(conex.rs.next());
            } catch (SQLException ex) {
               // JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\nErro:"+ex);
                JOptionPane.showMessageDialog(rootPane,"Não encontrado");
                jButtonAgendar.setEnabled(false);
                jButtonBaixa.setEnabled(false);
            }
       
            
           
            
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          jTable1.setModel(modelo);
          jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
          jTable1.getColumnModel().getColumn(0).setResizable(false);
          jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
          jTable1.getColumnModel().getColumn(1).setResizable(false);
          jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
          jTable1.getColumnModel().getColumn(2).setResizable(false);
          jTable1.getColumnModel().getColumn(3).setPreferredWidth(250);
          jTable1.getColumnModel().getColumn(3).setResizable(false);
          jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
          jTable1.getColumnModel().getColumn(4).setResizable(false);
          jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
          jTable1.getColumnModel().getColumn(5).setResizable(false);
          
          jTable1.getColumnModel().getColumn(6).setPreferredWidth(200);
          jTable1.getColumnModel().getColumn(6).setResizable(false);
          
          
          jTable1.getTableHeader().setReorderingAllowed(false);
          jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
          jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                  
    
       
    }   
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaMoradorEVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaMoradorEVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaMoradorEVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaMoradorEVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaMoradorEVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel codMorador;
    private javax.swing.JLabel codMu;
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JButton jButtonBaixa;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JComboBox jComboBoxApartamento;
    private javax.swing.JComboBox jComboBoxBloco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDataMudanca;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
