/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visao;

import Agendar.VerificarAgendamentoAdequado;
import Pesquisas.PesqPassagemDeServico;
import Pesquisas.PesqVeiculo;
import Pesquisas.PesqInterfone;
import Pesquisas.PesqMoradores;

import Pesquisas.PesqMudanca;
import Tabelas.TabelaBlocosApt;
import Tabelas.TabelaFuncionario;
import Tabelas.TabelaTelefone;
import Tabelas.TabelaUsuario;
import Tabelas.TabelaeTodosEXmoradores;
import CadastrarMudanca.Mudanca;
import Portaria.VisitaChave;
import CadastrarMoradores.Condominio;
import UsuarioLogin.FrmCadLogin;
import Portaria.PassagemDeServico;
import Portaria.Interfone;
import Portaria.Funcionario;
import ConfirmarEntradaEsaida.Saida;
import ConfirmarEntradaEsaida.EntradaMoradorEVeiculo;
import Alteracao.AlterarCondominio;
import Alteracao.AlteraVeiculo;

import Controle.ConectaBanco;
import Portaria.Visitante;
import SomenteEntradaVeiculo.AlugarGaragem;
import SomenteRetiradaMorador.RetirarSomenteMorador;
import SomenteSaidaVeiculo.RetirarSomenteVeiculo;
import Tabelas.TabelaCpfVisitante;
import Tabelas.TabelaVeiculos;
import Tabelas.TabelaVeiculosExmorador;
import Tabelas.TabelaeEXmorador;
import Tabelas.TabelaeEXmoradores;
import VerificarQualEoTipoDeConfirmacaoDeAgendamento.VerificarConfirmacaoAgendamento;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Eduardo
 */
public class Principal2 extends javax.swing.JFrame {

    ConectaBanco conexao = new ConectaBanco();
    public Principal2(String nome,String user) {
        initComponents();
        conexao.conexao();        
        Nome.setText(nome);
        User.setText(user);       
        
        
        this.setExtendedState(getExtendedState()| Principal2.MAXIMIZED_BOTH);
        
        
        
      
        
        URL url = this.getClass().getResource("/Imagens/condominio.jpg");  //coloca a imagem no lugar da tigela java
          Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
            this.setIconImage(imagemTitulo);
        
        
        
    }

    private Principal2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Condominio-SJ2");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/condominio2.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/condominio.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel4.setText("Condomínio São Jorge II");

        Nome.setBackground(new java.awt.Color(204, 204, 204));
        Nome.setForeground(new java.awt.Color(204, 204, 204));
        Nome.setText("Nome");

        User.setBackground(new java.awt.Color(204, 204, 204));
        User.setForeground(new java.awt.Color(204, 204, 204));
        User.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Nome)
                .addGap(40, 40, 40)
                .addComponent(User)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome)
                            .addComponent(User)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setForeground(new java.awt.Color(51, 51, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jMenu1.setText("Cadastrar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Moradores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("interfones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 153, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/57.png"))); // NOI18N
        jMenu2.setText("Portaria");

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(51, 51, 255));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jMenuItem4.setText("Cadastrar Visitantes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/75.png"))); // NOI18N
        jMenuItem5.setText("Diário de serviço");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem23.setForeground(new java.awt.Color(0, 153, 153));
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        jMenuItem23.setText("Controle de Visitantes");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem24.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        jMenuItem24.setText("Controle de Chaves");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem24);

        jMenuItem52.setForeground(new java.awt.Color(51, 51, 255));
        jMenuItem52.setText("Alugar Garagem");
        jMenuItem52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem52ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem52);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(51, 102, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/75.png"))); // NOI18N
        jMenu3.setText("Agendar Mudança");

        jMenuItem6.setText("Cadastrar Moradores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(204, 0, 51));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/76.png"))); // NOI18N
        jMenu4.setText("Confirmar Mudança ");

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(0, 153, 0));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/57.png"))); // NOI18N
        jMenuItem7.setText("Verificar Entrada de agendamento");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/56.png"))); // NOI18N
        jMenuItem8.setText("Saída de morador com veículo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem43.setForeground(new java.awt.Color(153, 51, 255));
        jMenuItem43.setText("Retira somente o morador");
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem43);

        jMenuItem51.setForeground(new java.awt.Color(153, 51, 255));
        jMenuItem51.setText("Retira somente o veículo");
        jMenuItem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem51ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem51);

        jMenuBar1.add(jMenu4);

        jMenu7.setForeground(new java.awt.Color(0, 153, 0));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesq.png"))); // NOI18N
        jMenu7.setText("Pequisar");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(0, 153, 0));
        jMenuItem10.setText("Moradores");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(0, 153, 0));
        jMenuItem11.setText("Veiculos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(0, 204, 0));
        jMenuItem12.setText("Mudanças");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(51, 51, 255));
        jMenuItem13.setText("Interfones");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem16.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem16.setText("Diário de ocorrências");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem16);

        jMenuBar1.add(jMenu7);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesq.png"))); // NOI18N
        jMenu5.setText("Tabelas");

        jMenuItem18.setText("Moradores");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuItem1.setText("Veiculos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem41.setText("Ex-Moradores");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem41);

        jMenuItem42.setText("Ex-Veiculos");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem42);

        jMenuBar1.add(jMenu5);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        jMenu8.setText("Alterar dados");

        jMenuItem20.setText("Dados dos Veiculos");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20);

        jMenuBar1.add(jMenu8);

        jMenu10.setForeground(new java.awt.Color(51, 204, 0));
        jMenu10.setText("Relatórios");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu10ActionPerformed(evt);
            }
        });

        jMenuItem27.setText("Moradores");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem27);

        jMenuItem32.setText("Relação de animais domésticos");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem32);

        jMenuItem36.setText("Carros ");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem36);

        jMenuItem38.setText("Motos");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem38);

        jMenuItem48.setText("Interfones");
        jMenuItem48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem48ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem48);

        jMenuItem49.setText("Diário de ocorrências");
        jMenuItem49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem49ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem49);

        jMenuItem9.setText("Bicicletas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem9);

        jMenuBar1.add(jMenu10);

        jMenu11.setForeground(new java.awt.Color(255, 102, 0));
        jMenu11.setText("Relatório de Mudanças");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu11ActionPerformed(evt);
            }
        });

        jMenuItem35.setText("Animais");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem35);

        jMenuItem37.setText("Carros da mudança");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem37);

        jMenuItem47.setText("Motos da mudança");
        jMenuItem47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem47ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem47);

        jMenuBar1.add(jMenu11);

        jMenu12.setForeground(new java.awt.Color(51, 153, 0));
        jMenu12.setText("Relatório visitas");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem40.setText("Visitas");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem40);

        jMenuItem45.setText("Entrada Saída");
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem45);

        jMenuBar1.add(jMenu12);

        jMenu13.setForeground(new java.awt.Color(255, 153, 0));
        jMenu13.setText("Relatório controle de chaves");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuItem44.setText("Agendamento de chaves");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem44);

        jMenuItem46.setText("Entrada e saida");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem46);

        jMenuBar1.add(jMenu13);

        jMenu9.setForeground(new java.awt.Color(255, 0, 0));
        jMenu9.setText("Sair");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(664, 664, 664)
                                .addComponent(jSeparator3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new Condominio().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new PassagemDeServico(Nome.getText(),User.getText()).setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
      new Funcionario().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
        new VerificarAgendamentoAdequado().setVisible(true);
       // new Mudanca().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        //new EntradaMoradorEVeiculo().setVisible(true);
        
        new VerificarConfirmacaoAgendamento().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new Saida().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new PesqMoradores().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        
        new PesqVeiculo().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new PesqMudanca().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        new PesqInterfone().setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        new PesqPassagemDeServico().setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        new TabelaBlocosApt().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        new AlteraVeiculo().setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
         new VisitaChave(Nome.getText(),User.getText()).setVisible(true);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new Interfone().setVisible(true); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        new Visitante(Nome.getText(),User.getText()).setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        // TODO add your handling code here:
        String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja Sair  ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;//Este é o Botao do NAO. Ira retornar para a Calculadora
        }
        
        if(resposta == 0){//Este é o Botao do SIM. Ira sair do seu Programa
            
            
     	dispose();
                	
        
        }
    }//GEN-LAST:event_jMenu9MouseClicked

    private void jMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu10ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu10ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        
        try{
        conexao.execultasql("select * from condominio");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/Moradores.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:
        
        try{
        conexao.execultasql("select * from condominio");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/Relação de Animais.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu11ActionPerformed
        // TODO add your handling code here:
        
                
              
    }//GEN-LAST:event_jMenu11ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        // TODO add your handling code here:
        
        try{
        conexao.execultasql("select * from mudanca");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/AnimaisMudança.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        // TODO add your handling code here:
        try{
        conexao.execultasql("select * from visita");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/Visitas.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
        // TODO add your handling code here:
         try{
        conexao.execultasql("select * from visita");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/VisitaEntradaSaida.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem45ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
        // TODO add your handling code here:
        
                
                 try{
        conexao.execultasql("select * from visita_chave");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/ControleChave.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        // TODO add your handling code here:
        
        
                 try{
        conexao.execultasql("select * from visita_chave");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/ControleEntradaSaida.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
        
        
                 try{
        conexao.execultasql("select * from veiculo");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/VeiculoAdesivado.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        // TODO add your handling code here:
        
          try{
        conexao.execultasql("select * from veiculo");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/motos.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        // TODO add your handling code here:
        
        
         try{
        conexao.execultasql("select * from veiculo_mudanca");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/VeiculoMudanca.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 

    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem47ActionPerformed
        // TODO add your handling code here:
         try{
        conexao.execultasql("select * from veiculo_mudanca");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/MotosMudanca.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
        
    }//GEN-LAST:event_jMenuItem47ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        new TabelaVeiculos().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem48ActionPerformed
        // TODO add your handling code here:
          try{
        conexao.execultasql("select * from interfone");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/Interfones.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        }
    }//GEN-LAST:event_jMenuItem48ActionPerformed

    private void jMenuItem49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem49ActionPerformed
        // TODO add your handling code here:
         try{
        conexao.execultasql("select * from diario_passagem_servico");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/PassagemServico.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
    }//GEN-LAST:event_jMenuItem49ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        // TODO add your handling code here:
        
       new TabelaeEXmorador().setVisible(true);
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        // TODO add your handling code here:
        new TabelaVeiculosExmorador().setVisible(true);
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem52ActionPerformed
        // TODO add your handling code here:
        new AlugarGaragem().setVisible(true);
    }//GEN-LAST:event_jMenuItem52ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        // TODO add your handling code here:
       new  RetirarSomenteMorador().setVisible(true);
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem51ActionPerformed
        // TODO add your handling code here:
        new RetirarSomenteVeiculo().setVisible(true);
    }//GEN-LAST:event_jMenuItem51ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        try{
        conexao.execultasql("select * from veiculo");
        JRResultSetDataSource relatResult = new JRResultSetDataSource(conexao.rs);
        JasperPrint jpPrint = JasperFillManager.fillReport("C:/Users/Delfino/Documents/NetBeansProjects/ProjetoSJ2/Relatorio/bicicletas.jasper",new HashMap(),relatResult);//("ireport/RelatorioBrancoCliente.jasper",new HashMap(),relatResult);
        JasperViewer jv = new JasperViewer(jpPrint,false);
        jv.setVisible(true);
        jv.toFront();
        }catch(JRException ex){
            
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!Erro:"+ex);
        } 
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
