/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Alteracao;

import Controle.ConectaBanco;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Eduardo
 */
public class AlteraVeiculo extends javax.swing.JFrame {

    ConectaBanco conex = new ConectaBanco();
    public AlteraVeiculo() {
        initComponents();
        
       
       
       
       
       
       
        URL url = this.getClass().getResource("/Imagens/condominio.jpg");  //coloca a imagem no lugar da tigela java
          Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
            this.setIconImage(imagemTitulo);
            
            //faz os botões serem acionados com a tecla enter
    AbstractAction action = new AbstractAction() {
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() instanceof JButton){
        JButton button = (JButton) e.getSource();
        button.doClick();        
        } else if(e.getSource() instanceof JComponent){
            JComponent component = (JComponent) e.getSource();
            component.transferFocus();
        }
    }
    };
    jButtonAlterar.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonAlterar.getActionMap().put("DoClick", action);
    jButtonPesquisar.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "DoClick");
    jButtonPesquisar.getActionMap().put("DoClick", action);
    
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldModeloCarroAdesivado = new javax.swing.JTextField();
        jTextFieldCorCarroAdesivado = new javax.swing.JTextField();
        jTextFieldMotoristaCarroAdesivado = new javax.swing.JTextField();
        jTextFieldCnhCarroAdesivado = new javax.swing.JTextField();
        jTextFieldPlacaCarroAdesivado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPlacaCarroNaoAdesivado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCorCarroNaoAdesivado = new javax.swing.JTextField();
        jTextFieldMotoristaCarroNaoAdesivado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCnhCarroNaoAdesivado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldModeloCarroNaoAdesivado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldModeloMoto1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCorMoto1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldMotoristaMoto1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCnhMoto1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldPlacaMoto1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jComboBoxApartamento = new javax.swing.JComboBox();
        jComboBoxBloco = new javax.swing.JComboBox();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldCodigoVeiculo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonAlterar = new javax.swing.JButton();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldModeloMoto2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCorMoto2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldMotoristaMoto2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldCnhMoto2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldPlacaMoto2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBicicleta = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jCheckBoxOculpada = new javax.swing.JCheckBox();
        jCheckBoxAlugada = new javax.swing.JCheckBox();
        jCheckBoxVazia = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabeGaragem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CondominioSJ2");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTextFieldModeloCarroAdesivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloCarroAdesivadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Modelo ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Cor ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Motorista");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("CNH ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Placa ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldModeloCarroAdesivado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTextFieldCorCarroAdesivado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMotoristaCarroAdesivado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCnhCarroAdesivado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPlacaCarroAdesivado, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModeloCarroAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCorCarroAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldMotoristaCarroAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCnhCarroAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPlacaCarroAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Modelo ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Cor ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Motorista ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("CNH ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Placa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCorCarroNaoAdesivado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTextFieldMotoristaCarroNaoAdesivado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldModeloCarroNaoAdesivado)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel21))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCnhCarroNaoAdesivado, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jTextFieldPlacaCarroNaoAdesivado))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModeloCarroNaoAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorCarroNaoAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMotoristaCarroNaoAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCnhCarroNaoAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldPlacaCarroNaoAdesivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Modelo");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Cor");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Motorista");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("CNH");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Placa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldModeloMoto1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jTextFieldCorMoto1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMotoristaMoto1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCnhMoto1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPlacaMoto1))
                .addGap(73, 73, 73))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldModeloMoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldCorMoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldMotoristaMoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldCnhMoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldPlacaMoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jComboBoxApartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "APARTAMENTO 101", "APARTAMENTO 102", "APARTAMENTO 103", "APARTAMENTO 104", "APARTAMENTO 201", "APARTAMENTO 202", "APARTAMENTO 203", "APARTAMENTO 204", "APARTAMENTO 301", "APARTAMENTO 302", "APARTAMENTO 303", "APARTAMENTO 304", "APARTAMENTO 401", "APARTAMENTO 402", "APARTAMENTO 403", "APARTAMENTO 404", " ", " " }));

        jComboBoxBloco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLOCO A", "BLOCO B", "BLOCO C", "BLOCO D", "BLOCO F", "BLOCO G", "BLOCO H", "BLOCO I", "BLOCO J", "BLOCO K", " ", " " }));
        jComboBoxBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBlocoActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesq.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cod Veiculo");

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/back.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Descrição:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescricao))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldCodigoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jComboBoxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jTextFieldCodigoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Modelo");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Cor");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Motorista");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("CNH");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Placa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldCorMoto2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jTextFieldMotoristaMoto2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCnhMoto2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldModeloMoto2)
                    .addComponent(jTextFieldPlacaMoto2))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldModeloMoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldCorMoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldMotoristaMoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldCnhMoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldPlacaMoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 204, 0));
        jLabel23.setText("CARRO  ADESIVADO");

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 204, 0));
        jLabel22.setText("CARRO NÃO ADESIVADO");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 204, 0));
        jLabel24.setText("MOTO 1");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 204, 0));
        jLabel25.setText("MOTO 2");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 153, 102));
        jLabel28.setText("Bicicleta");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel23)
                .addGap(102, 102, 102)
                .addComponent(jLabel22)
                .addGap(153, 153, 153)
                .addComponent(jLabel24)
                .addGap(204, 204, 204)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(95, 95, 95))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28))
                .addGap(20, 20, 20))
        );

        jTextAreaBicicleta.setColumns(20);
        jTextAreaBicicleta.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextAreaBicicleta.setForeground(new java.awt.Color(102, 102, 255));
        jTextAreaBicicleta.setRows(5);
        jScrollPane1.setViewportView(jTextAreaBicicleta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator5)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1))
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCheckBoxOculpada.setForeground(new java.awt.Color(51, 102, 255));
        jCheckBoxOculpada.setText("Ocupada");
        jCheckBoxOculpada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxOculpadaItemStateChanged(evt);
            }
        });

        jCheckBoxAlugada.setForeground(new java.awt.Color(51, 102, 255));
        jCheckBoxAlugada.setText("Alugada");
        jCheckBoxAlugada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxAlugadaItemStateChanged(evt);
            }
        });

        jCheckBoxVazia.setForeground(new java.awt.Color(51, 102, 255));
        jCheckBoxVazia.setText("vazio");
        jCheckBoxVazia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxVaziaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jCheckBoxOculpada)
                .addGap(40, 40, 40)
                .addComponent(jCheckBoxAlugada)
                .addGap(44, 44, 44)
                .addComponent(jCheckBoxVazia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxVazia)
                    .addComponent(jCheckBoxAlugada)
                    .addComponent(jCheckBoxOculpada)))
        );

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Alterar os dados");

        jLabeGaragem.setText("garagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabeGaragem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeGaragem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldModeloCarroAdesivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloCarroAdesivadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloCarroAdesivadoActionPerformed

    private void jComboBoxBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBlocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBlocoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        
        conex.conexao();
            
            
            conex.execultasql("select * from veiculo where bloco='"+jComboBoxBloco.getSelectedItem()+"' and numeroApartamento = '"+jComboBoxApartamento.getSelectedItem()+"'");
            
        try {
           
            conex.rs.first();
            
            
       jTextFieldCodigoVeiculo.setText(String.valueOf(conex.rs.getInt("idveiculo")));
       jTextFieldModeloCarroAdesivado.setText(conex.rs.getString("modelo_carroAdesivado"));
       jTextFieldCorCarroAdesivado.setText(conex.rs.getString("cor_carroAdesivado"));
       jTextFieldMotoristaCarroAdesivado.setText(conex.rs.getString("motorista_carroAdesivado"));
       jTextFieldCnhCarroAdesivado.setText(conex.rs.getString("cnh_motorista_carroAdesivado"));
       jTextFieldPlacaCarroAdesivado.setText(conex.rs.getString("placa_carroAdesivado"));
       
       
      
       jTextFieldModeloCarroNaoAdesivado.setText(conex.rs.getString("modelo_carroNaoAdesivado"));
       jTextFieldCorCarroNaoAdesivado.setText(conex.rs.getString("cor_carroNaoAdesivado"));
       jTextFieldMotoristaCarroNaoAdesivado.setText(conex.rs.getString("motorista_carroNaoAdesivado"));
       jTextFieldCnhCarroNaoAdesivado.setText(conex.rs.getString("cnh_motorista_carroNaoAdesivado"));
       jTextFieldPlacaCarroNaoAdesivado.setText(conex.rs.getString("placa_carroNaoAdesivado"));
       
       
       jTextFieldModeloMoto1.setText(conex.rs.getString("modelo_moto1"));
       jTextFieldCorMoto1.setText(conex.rs.getString("cor_moto1"));
       jTextFieldMotoristaMoto1.setText(conex.rs.getString("motorista_moto1"));
       jTextFieldCnhMoto1.setText(conex.rs.getString("cnh_motorista_moto1"));
       jTextFieldPlacaMoto1.setText(conex.rs.getString("placa_moto1"));
       
       
       jTextFieldModeloMoto2.setText(conex.rs.getString("modelo_moto2"));
       jTextFieldCorMoto2.setText(conex.rs.getString("cor_moto2"));
       jTextFieldMotoristaMoto2.setText(conex.rs.getString("motorista_moto2"));
       jTextFieldCnhMoto2.setText(conex.rs.getString("cnh_motorista_moto2"));
       jTextFieldPlacaMoto2.setText(conex.rs.getString("placa_moto2"));
       jLabeGaragem.setText(conex.rs.getString("garagem"));
       jTextFieldDescricao.setText(conex.rs.getString("descricao"));
       jTextAreaBicicleta.setText(conex.rs.getString("bicicleta"));     
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Não foi possivel");
            
            
            
            
       jTextFieldCodigoVeiculo.setText("");
       jTextFieldModeloCarroAdesivado.setText("");
       jTextFieldCorCarroAdesivado.setText("");
       jTextFieldMotoristaCarroAdesivado.setText("");
       jTextFieldCnhCarroAdesivado.setText("");
       jTextFieldPlacaCarroAdesivado.setText("");
       
       
      
       jTextFieldModeloCarroNaoAdesivado.setText("");
       jTextFieldCorCarroNaoAdesivado.setText("");
       jTextFieldMotoristaCarroNaoAdesivado.setText("");
       jTextFieldCnhCarroNaoAdesivado.setText("");
       jTextFieldPlacaCarroNaoAdesivado.setText("");
       
       
       jTextFieldModeloMoto1.setText("");
       jTextFieldCorMoto1.setText("");
       jTextFieldMotoristaMoto1.setText("");
       jTextFieldCnhMoto1.setText("");
       jTextFieldPlacaMoto1.setText("");
       
       
       jTextFieldModeloMoto2.setText("");
       jTextFieldCorMoto2.setText("");
       jTextFieldMotoristaMoto2.setText("");
       jTextFieldCnhMoto2.setText("");
       jTextFieldPlacaMoto2.setText("");
       jTextAreaBicicleta.setText("");
            
            
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        
        if(jTextFieldCodigoVeiculo.getText().equals("")){
             JOptionPane.showMessageDialog(rootPane,"Busque um bloco e apartamento para consultar e Alterar"); 
        }else{
        
        String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja Editar ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;  //Este é o Botao do NAO. Ira retornar para a Calculadora
        }
        
        if(resposta == 0){  try {
            //Este é o Botao do SIM. Ira sair do seu Programa
            
            PreparedStatement alterarVeiculo = conex.conn.prepareStatement("call alteraVeiculo('"+jTextFieldCodigoVeiculo.getText()+"','"+jTextFieldModeloCarroAdesivado.getText()+"','"+jTextFieldCorCarroAdesivado.getText()+"','"+jTextFieldMotoristaCarroAdesivado.getText()+"','"+jTextFieldCnhCarroAdesivado.getText()+"','"+jTextFieldPlacaCarroAdesivado.getText()+"'   ,'"+jTextFieldModeloCarroNaoAdesivado.getText()+"','"+jTextFieldCorCarroNaoAdesivado.getText()+"','"+jTextFieldMotoristaCarroNaoAdesivado.getText()+"','"+jTextFieldCnhCarroNaoAdesivado.getText()+"','"+jTextFieldPlacaCarroNaoAdesivado.getText()+"'    ,'"+jTextFieldModeloMoto1.getText()+"','"+jTextFieldCorMoto1.getText()+"','"+jTextFieldMotoristaMoto1.getText()+"','"+jTextFieldCnhMoto1.getText()+"','"+jTextFieldPlacaMoto1.getText()+"'   ,'"+jTextFieldModeloMoto2.getText()+"','"+jTextFieldCorMoto2.getText()+"','"+jTextFieldMotoristaMoto2.getText()+"','"+jTextFieldCnhMoto2.getText()+"','"+jTextFieldPlacaMoto2.getText()+"','"+jLabeGaragem.getText()+"','"+jTextFieldDescricao.getText()+"','"+jTextAreaBicicleta.getText()+"')");
            
            alterarVeiculo.execute();
            
             JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
             dispose();
             
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao Alterar"+ex);
            }
                
        }
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jCheckBoxOculpadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxOculpadaItemStateChanged
        // TODO add your handling code here:

        String a = (String)jCheckBoxOculpada.getText();
        jLabeGaragem.setText(a);

        jCheckBoxAlugada.setSelected(false);
        jCheckBoxVazia.setSelected(false);

        jTextFieldModeloCarroAdesivado.setText("");
        jTextFieldCorCarroAdesivado.setText("");
        jTextFieldMotoristaCarroAdesivado.setText("");
        jTextFieldCnhCarroAdesivado.setText("");
        jTextFieldPlacaCarroAdesivado.setText("");
        jTextFieldModeloCarroNaoAdesivado.setText("");
        jTextFieldCorCarroNaoAdesivado.setText("");
        jTextFieldMotoristaCarroNaoAdesivado.setText("");
        jTextFieldCnhCarroNaoAdesivado.setText("");
        jTextFieldPlacaCarroNaoAdesivado.setText("");
        jTextFieldModeloMoto1.setText("");
        jTextFieldCorMoto1.setText("");
        jTextFieldMotoristaMoto1.setText("");
        jTextFieldCnhMoto1.setText("");
        jTextFieldPlacaMoto1.setText("");
        jTextFieldModeloMoto2.setText("");
        jTextFieldCorMoto2.setText("");
        jTextFieldMotoristaMoto2.setText("");
        jTextFieldCnhMoto2.setText("");
        jTextFieldPlacaMoto2.setText("");
        jTextAreaBicicleta.setText("");
        jTextFieldDescricao.setEnabled(false);

        jTextFieldModeloCarroAdesivado.setEnabled(!false);
        jTextFieldCorCarroAdesivado.setEnabled(!false);
        jTextFieldMotoristaCarroAdesivado.setEnabled(!false);
        jTextFieldCnhCarroAdesivado.setEnabled(!false);
        jTextFieldPlacaCarroAdesivado.setEnabled(!false);
        jTextFieldModeloCarroNaoAdesivado.setEnabled(!false);
        jTextFieldCorCarroNaoAdesivado.setEnabled(!false);
        jTextFieldMotoristaCarroNaoAdesivado.setEnabled(!false);
        jTextFieldCnhCarroNaoAdesivado.setEnabled(!false);
        jTextFieldPlacaCarroNaoAdesivado.setEnabled(!false);
        jTextFieldModeloMoto1.setEnabled(!false);
        jTextFieldCorMoto1.setEnabled(!false);
        jTextFieldMotoristaMoto1.setEnabled(!false);
        jTextFieldCnhMoto1.setEnabled(!false);
        jTextFieldPlacaMoto1.setEnabled(!false);
        jTextFieldModeloMoto2.setEnabled(!false);
        jTextFieldCorMoto2.setEnabled(!false);
        jTextFieldMotoristaMoto2.setEnabled(!false);
        jTextFieldCnhMoto2.setEnabled(!false);
        jTextFieldPlacaMoto2.setEnabled(!false);
        jTextAreaBicicleta.setEnabled(!false);
        
    }//GEN-LAST:event_jCheckBoxOculpadaItemStateChanged

    private void jCheckBoxAlugadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxAlugadaItemStateChanged
        // TODO add your handling code here:
        String a = (String)jCheckBoxAlugada.getText();
        jLabeGaragem.setText(a);

        jCheckBoxOculpada.setSelected(false);
        jCheckBoxVazia.setSelected(false);

        jTextFieldModeloCarroAdesivado.setText("");
        jTextFieldCorCarroAdesivado.setText("");
        jTextFieldMotoristaCarroAdesivado.setText("");
        jTextFieldCnhCarroAdesivado.setText("");
        jTextFieldPlacaCarroAdesivado.setText("");
        jTextFieldModeloCarroNaoAdesivado.setText("");
        jTextFieldCorCarroNaoAdesivado.setText("");
        jTextFieldMotoristaCarroNaoAdesivado.setText("");
        jTextFieldCnhCarroNaoAdesivado.setText("");
        jTextFieldPlacaCarroNaoAdesivado.setText("");
        jTextFieldModeloMoto1.setText("");
        jTextFieldCorMoto1.setText("");
        jTextFieldMotoristaMoto1.setText("");
        jTextFieldCnhMoto1.setText("");
        jTextFieldPlacaMoto1.setText("");
        jTextFieldModeloMoto2.setText("");
        jTextFieldCorMoto2.setText("");
        jTextFieldMotoristaMoto2.setText("");
        jTextFieldCnhMoto2.setText("");
        jTextFieldPlacaMoto2.setText("");
        jTextAreaBicicleta.setText("");

        jTextFieldDescricao.setEnabled(!false);
        jTextFieldModeloCarroAdesivado.setEnabled(!false);
        jTextFieldCorCarroAdesivado.setEnabled(!false);
        jTextFieldMotoristaCarroAdesivado.setEnabled(!false);
        jTextFieldCnhCarroAdesivado.setEnabled(!false);
        jTextFieldPlacaCarroAdesivado.setEnabled(!false);
        jTextFieldModeloCarroNaoAdesivado.setEnabled(!false);
        jTextFieldCorCarroNaoAdesivado.setEnabled(!false);
        jTextFieldMotoristaCarroNaoAdesivado.setEnabled(!false);
        jTextFieldCnhCarroNaoAdesivado.setEnabled(!false);
        jTextFieldPlacaCarroNaoAdesivado.setEnabled(!false);
        jTextFieldModeloMoto1.setEnabled(!false);
        jTextFieldCorMoto1.setEnabled(!false);
        jTextFieldMotoristaMoto1.setEnabled(!false);
        jTextFieldCnhMoto1.setEnabled(!false);
        jTextFieldPlacaMoto1.setEnabled(!false);
        jTextFieldModeloMoto2.setEnabled(!false);
        jTextFieldCorMoto2.setEnabled(!false);
        jTextFieldMotoristaMoto2.setEnabled(!false);
        jTextFieldCnhMoto2.setEnabled(!false);
        jTextFieldPlacaMoto2.setEnabled(!false);
        jTextAreaBicicleta.setEnabled(!false);
        
    }//GEN-LAST:event_jCheckBoxAlugadaItemStateChanged

    private void jCheckBoxVaziaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxVaziaItemStateChanged
        // TODO add your handling code here:

        String a = (String)jCheckBoxVazia.getText();
        jLabeGaragem.setText(a);

        jCheckBoxAlugada.setSelected(false);
        jCheckBoxOculpada.setSelected(false);

        jTextFieldModeloCarroAdesivado.setText("");
        jTextFieldCorCarroAdesivado.setText("");
        jTextFieldMotoristaCarroAdesivado.setText("");
        jTextFieldCnhCarroAdesivado.setText("");
        jTextFieldPlacaCarroAdesivado.setText("");
        jTextFieldModeloCarroNaoAdesivado.setText("");
        jTextFieldCorCarroNaoAdesivado.setText("");
        jTextFieldMotoristaCarroNaoAdesivado.setText("");
        jTextFieldCnhCarroNaoAdesivado.setText("");
        jTextFieldPlacaCarroNaoAdesivado.setText("");
        jTextFieldModeloMoto1.setText("");
        jTextFieldCorMoto1.setText("");
        jTextFieldMotoristaMoto1.setText("");
        jTextFieldCnhMoto1.setText("");
        jTextFieldPlacaMoto1.setText("");
        jTextFieldModeloMoto2.setText("");
        jTextFieldCorMoto2.setText("");
        jTextFieldMotoristaMoto2.setText("");
        jTextFieldCnhMoto2.setText("");
        jTextFieldPlacaMoto2.setText("");
        jTextAreaBicicleta.setText("");

        jTextFieldModeloCarroAdesivado.setText(a);
        jTextFieldCorCarroAdesivado.setText(a);
        jTextFieldMotoristaCarroAdesivado.setText(a);
        jTextFieldCnhCarroAdesivado.setText(a);
        jTextFieldPlacaCarroAdesivado.setText(a);
        jTextFieldModeloCarroNaoAdesivado.setText(a);
        jTextFieldCorCarroNaoAdesivado.setText(a);
        jTextFieldMotoristaCarroNaoAdesivado.setText(a);
        jTextFieldCnhCarroNaoAdesivado.setText(a);
        jTextFieldPlacaCarroNaoAdesivado.setText(a);
        jTextFieldModeloMoto1.setText(a);
        jTextFieldCorMoto1.setText(a);
        jTextFieldMotoristaMoto1.setText(a);
        jTextFieldCnhMoto1.setText(a);
        jTextFieldPlacaMoto1.setText(a);
        jTextFieldModeloMoto2.setText(a);
        jTextFieldCorMoto2.setText(a);
        jTextFieldMotoristaMoto2.setText(a);
        jTextFieldCnhMoto2.setText(a);
        jTextFieldPlacaMoto2.setText(a);
        jTextFieldDescricao.setText(a);
        jTextFieldDescricao.setEnabled(false);
        

    }//GEN-LAST:event_jCheckBoxVaziaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteraVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JCheckBox jCheckBoxAlugada;
    private javax.swing.JCheckBox jCheckBoxOculpada;
    private javax.swing.JCheckBox jCheckBoxVazia;
    private javax.swing.JComboBox jComboBoxApartamento;
    private javax.swing.JComboBox jComboBoxBloco;
    private javax.swing.JLabel jLabeGaragem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextAreaBicicleta;
    private javax.swing.JTextField jTextFieldCnhCarroAdesivado;
    private javax.swing.JTextField jTextFieldCnhCarroNaoAdesivado;
    private javax.swing.JTextField jTextFieldCnhMoto1;
    private javax.swing.JTextField jTextFieldCnhMoto2;
    private javax.swing.JTextField jTextFieldCodigoVeiculo;
    private javax.swing.JTextField jTextFieldCorCarroAdesivado;
    private javax.swing.JTextField jTextFieldCorCarroNaoAdesivado;
    private javax.swing.JTextField jTextFieldCorMoto1;
    private javax.swing.JTextField jTextFieldCorMoto2;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldModeloCarroAdesivado;
    private javax.swing.JTextField jTextFieldModeloCarroNaoAdesivado;
    private javax.swing.JTextField jTextFieldModeloMoto1;
    private javax.swing.JTextField jTextFieldModeloMoto2;
    private javax.swing.JTextField jTextFieldMotoristaCarroAdesivado;
    private javax.swing.JTextField jTextFieldMotoristaCarroNaoAdesivado;
    private javax.swing.JTextField jTextFieldMotoristaMoto1;
    private javax.swing.JTextField jTextFieldMotoristaMoto2;
    private javax.swing.JTextField jTextFieldPlacaCarroAdesivado;
    private javax.swing.JTextField jTextFieldPlacaCarroNaoAdesivado;
    private javax.swing.JTextField jTextFieldPlacaMoto1;
    private javax.swing.JTextField jTextFieldPlacaMoto2;
    // End of variables declaration//GEN-END:variables
}
